spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8484/realms/mmo-dev
          jwk-set-uri: http://localhost:8484/realms/mmo-dev/protocol/openid-connect/certs

server:
  port: 8082
