spring:
  application:
    name: "MMO game server"

  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri:
#          jwk-set-uri:

server:
  details:
#    self-url: http://server-root-url.lan/
#    backend-url: http://backend-root-url.lan/
#    backend-token: backend-token-string
