spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mmo_backend
    username: postgres
    password: postgres

server:
  port: 8081

springdoc:
  swagger-ui:
    oauth:
      clientId: mmo-dev-frontend
      authorizationUrl: http://localhost:8484/realms/mmo-dev/protocol/openid-connect/auth
      tokenUrl: http://localhost:8484/realms/mmo-dev/protocol/openid-connect/token
