spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mmo_backend
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8484/realms/mmo-dev
          jwk-set-uri: http://localhost:8484/realms/mmo-dev/protocol/openid-connect/certs

server:
  port: 8081

springdoc:
  swagger-ui:
    oauth:
      clientId: mmo-dev-frontend
      authorizationUrl: http://localhost:8484/realms/mmo-dev/protocol/openid-connect/auth
      tokenUrl: http://localhost:8484/realms/mmo-dev/protocol/openid-connect/token
